// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview An anomaly detection AI agent for salary data.
 *
 * - detectSalaryAnomalies - A function that handles the salary anomaly detection process.
 * - DetectSalaryAnomaliesInput - The input type for the detectSalaryAnomalies function.
 * - DetectSalaryAnomaliesOutput - The return type for the detectSalaryAnomalies function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const DetectSalaryAnomaliesInputSchema = z.array(
  z.object({
    Emp_ID: z.string(),
    Name: z.string(),
    Department: z.string(),
    Base_Salary: z.number(),
    Bonus: z.number(),
    Deductions: z.number(),
    Total_Salary: z.number(),
    Predicted_Salary: z.number(),
  })
).describe('An array of employee salary data.');

export type DetectSalaryAnomaliesInput = z.infer<typeof DetectSalaryAnomaliesInputSchema>;

const DetectSalaryAnomaliesOutputSchema = z.array(
  z.object({
    Emp_ID: z.string(),
    Name: z.string(),
    Department: z.string(),
    Base_Salary: z.number(),
    Bonus: z.number(),
    Deductions: z.number(),
    Total_Salary: z.number(),
    Predicted_Salary: z.number(),
    Anomaly_Label: z.string().describe("The anomaly label, which can be 'Anomaly' or 'Normal'."),
  })
).describe('An array of employee salary data with anomaly labels.');

export type DetectSalaryAnomaliesOutput = z.infer<typeof DetectSalaryAnomaliesOutputSchema>;

export async function detectSalaryAnomalies(input: DetectSalaryAnomaliesInput): Promise<DetectSalaryAnomaliesOutput> {
  return detectSalaryAnomaliesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'detectSalaryAnomaliesPrompt',
  input: {schema: DetectSalaryAnomaliesInputSchema},
  output: {schema: DetectSalaryAnomaliesOutputSchema},
  prompt: `You are an expert in anomaly detection, specializing in identifying unusual patterns in salary data.

You are given an array of employee salary data with the following fields: Emp_ID, Name, Department, Base_Salary, Bonus, Deductions, Total_Salary, Predicted_Salary. Your task is to analyze the salary data and identify any anomalies in salary distribution. Label each employee's data as 'Anomaly' or 'Normal' in the Anomaly_Label field.

Here is the salary data:

{{#each this}}
Emp_ID: {{Emp_ID}}, Name: {{Name}}, Department: {{Department}}, Base_Salary: {{Base_Salary}}, Bonus: {{Bonus}}, Deductions: {{Deductions}}, Total_Salary: {{Total_Salary}}, Predicted_Salary: {{Predicted_Salary}}
{{/each}}

Return the data with the Anomaly_Label column.

Ensure that the output is a valid JSON array of objects.`,  
});

const detectSalaryAnomaliesFlow = ai.defineFlow(
  {
    name: 'detectSalaryAnomaliesFlow',
    inputSchema: DetectSalaryAnomaliesInputSchema,
    outputSchema: DetectSalaryAnomaliesOutputSchema,
  },
  async input => {
    try {
      const {output} = await prompt(input);
      return output!;
    } catch (error) {
      console.error('Error in detectSalaryAnomaliesFlow:', error);
      throw new Error(`Failed to detect salary anomalies: ${error}`);
    }
  }
);







